<?php

/**
 * Company: Yee Technologies Pvt. Ltd. < www.yeetechnologies.com >
 * Author : Praveen Shivhare < praveen.tuffgeekers@gmail.com >
 */
 
/**
 * This is the model base class for the table "{{report}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Report".
 *
 * Columns in table "{{report}}" available as properties of the model,
 * followed by relations of table "{{report}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property integer $state_id
 * @property integer $type_id
 * @property string $expiry_duration
 *
 * @property ReportCause[] $reportCauses
 */
abstract class BaseReport extends GxActiveRecord {

	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{report}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Report|Reports', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, expiry_duration', 'required'),
			array('state_id, type_id', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>255),
			array('expiry_duration', 'length', 'max'=>128),
			array('state_id, type_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, state_id, type_id, expiry_duration', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'reportCauses' => array(self::HAS_MANY, 'ReportCause', 'report_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'state_id' => Yii::t('app', 'State'),
			'type_id' => Yii::t('app', 'Type'),
			'expiry_duration' => Yii::t('app', 'Expiry Duration'),
			'reportCauses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('expiry_duration', $this->expiry_duration, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}